"""add parent_id/displayorder to checkpoint_section

Revision ID: 4f1470385023
Revises: be31def645ad
Create Date: 2026-08-30 13:39:44.756065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1470385023'
down_revision = 'be31def645ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkpoint_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('displayorder', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkpoint_section', schema=None) as batch_op:
        batch_op.drop_column('displayorder')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
