"""Add User To Checkpoint

Revision ID: be31def645ad
Revises: 5c2e6d98519b
Create Date: 2026-08-09 20:48:23.410637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be31def645ad'
down_revision = '5c2e6d98519b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkpoint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key('fk_checkpoint_users', 'users', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkpoint', schema=None) as batch_op:
        batch_op.drop_constraint('fk_checkpoint_users', type_='foreignkey')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
